### ISSUE TITLE
Nieuwe HTML voor nieuw ontwerp

### ISSUE THREAD

**Issue by yamenAl** [yamenAl/your-tribe-profile-card#2]
![IMG_8634](https://github.com/user-attachments/assets/a5fd396c-0410-4eba-a477-3cb668eab856)

**Comment by DorienD** [comment]
Hoi Yamen,

Een paar verbeterpuntjes voor je breakdown:
- Probeer vierkante vlakken om de html elementen te tekenen, je hebt nu 1 roze vierkant gebruikt. Zet om elk element eens zo'n vierkant
- Goed om te weten, er bestaat geen `p2` alleen `p`
- Je kunt je afvragen of je een `p` nodig hebt in een `li`

En nog een tip, neem ook wat dummy CSS code mee in je breakdown dan kun je alvast een gameplan maken hoe met CSS wilt gaan werken.
